theme: jekyll-theme-slate
url: "https://challenge.inspire-helsinki-2019.fi" # the base hostname & protocol for your site
home: "https://inspire-helsinki-2019.fi"
google_analytics: UA-21595267-11
plugins:
  - jekyll-sitemap
